language: python

dist: focal

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y apache2-utils
  - mkdir -p ~/.docker/cli-plugins/
  - wget -O ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
  - chmod +x ~/.docker/cli-plugins/docker-buildx

install:
  - pip install -r requirements-test.txt
  - pip install -e .

script:
  - make test
  - make test-integration
