language: python

dist: focal

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y apache2-utils

install:
  - pip install -r requirements-test.txt
  - pip install .

script:
  - make test
  - make test-integration
