#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys

from regview import regview

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    try:
        sys.exit(regview.main())
    except KeyboardInterrupt:
        sys.exit(1)
